# Etapa 1: Build do Backend
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copiar arquivos necessários para o build
COPY photo-map/pom.xml .
COPY photo-map/src ./src

# Construir o JAR
RUN mvn clean package -DskipTests

# Etapa 2: Execução do Backend
FROM openjdk:21-jdk-slim
WORKDIR /app

# Copiar o JAR gerado na etapa de build
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8092
ENTRYPOINT ["java", "-jar", "app.jar"]
